// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtveCRVTDSvky6SoqhO-4osg6R7ff_l_o',
    appId: '1:984416317446:web:2d931df18203fbeb109387',
    messagingSenderId: '984416317446',
    projectId: 'doindia-f8fd5',
    authDomain: 'doindia-f8fd5.firebaseapp.com',
    storageBucket: 'doindia-f8fd5.appspot.com',
    measurementId: 'G-ELXTP2W1BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVEBBHrfk23CJjAWjO4_nylEPB_RxFs8',
    appId: '1:984416317446:android:997899b2eec63460109387',
    messagingSenderId: '984416317446',
    projectId: 'doindia-f8fd5',
    storageBucket: 'doindia-f8fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEuTuFpq7lau48S_cISPL2BLpz2ihslM',
    appId: '1:984416317446:ios:43b289021dc8e9f9109387',
    messagingSenderId: '984416317446',
    projectId: 'doindia-f8fd5',
    storageBucket: 'doindia-f8fd5.appspot.com',
    iosBundleId: 'com.dashmesh.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEuTuFpq7lau48S_cISPL2BLpz2ihslM',
    appId: '1:984416317446:ios:43b289021dc8e9f9109387',
    messagingSenderId: '984416317446',
    projectId: 'doindia-f8fd5',
    storageBucket: 'doindia-f8fd5.appspot.com',
    iosBundleId: 'com.dashmesh.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtveCRVTDSvky6SoqhO-4osg6R7ff_l_o',
    appId: '1:984416317446:web:6cbd7d97ffea67d1109387',
    messagingSenderId: '984416317446',
    projectId: 'doindia-f8fd5',
    authDomain: 'doindia-f8fd5.firebaseapp.com',
    storageBucket: 'doindia-f8fd5.appspot.com',
    measurementId: 'G-GJD1J7JSGY',
  );
}
